/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store;

import Dao.CategoryDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author JovenLoba
 */
public class Category extends javax.swing.JFrame {

  /**
   * Creates new form Category
   */
  public Category() {
    initComponents();
    frameSizeLocation();
  }
    private void frameSizeLocation() {
    int  height =  global.GlobalVariables.windowCategoryHeight;
    int  width =  global.GlobalVariables.windowCategoryWidth;
    int x = 600;
    int y = 250;
//    setSize(width, height);
//    setLocation(200,100);
    setBounds(x,y,width,height);

  }    


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    btn_Save = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    txtCode = new javax.swing.JTextField();
    txtName = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLabel5 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setResizable(false);
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
    jButton1.setText("Exit");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 90, 40));

    jPanel1.setBackground(new java.awt.Color(240, 255, 204));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setText("Category Code");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 42, -1, -1));

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setText("Name");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 124, -1, -1));

    btn_Save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
    btn_Save.setText("SAve");
    btn_Save.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_SaveActionPerformed(evt);
      }
    });
    jPanel1.add(btn_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

    jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
    jButton3.setText("Clear");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

    txtCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jPanel1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 75, 160, -1));

    txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 165, -1));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 330));

    jPanel2.setBackground(new java.awt.Color(233, 255, 204));
    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Id", "Code", "Name"
      }
    ));
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jTable1);

    jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 370, 250));

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 430, 330));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
    jLabel5.setText("jLabel5");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   clear();
  }//GEN-LAST:event_jButton3ActionPerformed

  private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
 DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
    ArrayList<model.Category> list = CategoryDao.getAllRecords();
    Iterator<model.Category> itr = list.iterator();
    while (itr.hasNext()){
      model.Category category = itr.next();
      dtm.addRow(new Object[]{
        category.getId(), category.getCode(),
        category.getName()

      });
    }
  }//GEN-LAST:event_formComponentShown

  private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
    String categoryCode = txtCode.getText();  
    String categoryName = txtName.getText();
      model.Category category = new model.Category();
      category.setCode(categoryCode);
      category.setName(categoryName);
      CategoryDao.save(category);
      clear();
      setVisible(false);
      new Category().setVisible(true);
  }//GEN-LAST:event_btn_SaveActionPerformed

  private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    int index = jTable1.getSelectedRow();
    TableModel model = jTable1.getModel();
    String id = model.getValueAt(index, 0).toString();
    String name = model.getValueAt(index, 1).toString();
    int a = JOptionPane.showConfirmDialog(null,"Confirm to delete '"+name+"'", "Select", JOptionPane.YES_NO_OPTION);
    if (a==0){
      CategoryDao.deleteCategoryRecord(id);
      setVisible(false);
      new Category().setVisible(true);
      
    }
  }//GEN-LAST:event_jTable1MouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Category().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Save;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField txtCode;
  private javax.swing.JTextField txtName;
  // End of variables declaration//GEN-END:variables

  private void clear() {
    txtCode.setText("");
    txtName.setText("");
    btn_Save.setEnabled(false);
            
    
   
  }
}
