package store;


import Database.DatabaseHandler;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JovenLoba
 */
public class Home extends javax.swing.JFrame {
  
  DatabaseHandler handler;  
  public  String user_email="";

  /**
   * Creates new form Home
   */
  public Home() {
   initComponents();
   handler =  DatabaseHandler.getInstance();
   initial_setup();
  }
  
  public Home(String email) {
    initComponents();
    handler =  DatabaseHandler.getInstance();
    user_email = email;
    lbl_Email.setText(user_email);
    initial_setup();
 
  }
    
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    lbl_Email = new javax.swing.JLabel();
    panel_admin = new javax.swing.JPanel();
    btnCategory = new javax.swing.JButton();
    btnNewProduct = new javax.swing.JButton();
    btnViewEditDelete = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(100, 500));
    setUndecorated(true);
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
    jButton1.setText("Exit");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, 120, 35));

    lbl_Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    getContentPane().add(lbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 263, 40));

    panel_admin.setBackground(new java.awt.Color(236, 255, 255));
    panel_admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnCategory.setText("Category");
    btnCategory.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCategoryActionPerformed(evt);
      }
    });
    panel_admin.add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 193, 37));

    btnNewProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnNewProduct.setText("New Product");
    btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNewProductActionPerformed(evt);
      }
    });
    panel_admin.add(btnNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 193, 40));

    btnViewEditDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnViewEditDelete.setText("View Edit Delete");
    btnViewEditDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnViewEditDeleteActionPerformed(evt);
      }
    });
    panel_admin.add(btnViewEditDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 193, 40));

    getContentPane().add(panel_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, 690, 80));

    jPanel1.setBackground(new java.awt.Color(227, 242, 242));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton2.setText("Change Password");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 30));

    jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton3.setText("View  Bill and  Placed Order");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, 30));

    jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton4.setText("Place Order");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 30));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, 190));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/storeHome.png"))); // NOI18N
    jLabel1.setText("jLabel1");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 810));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   int a = JOptionPane.showConfirmDialog(null, "Do you want to exit Application","select",JOptionPane.YES_NO_OPTION);
    if (a == 0){
      System.exit(0);
    }else{
      System.out.println("Pressed no");
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
    new Category().setVisible(true);
  }//GEN-LAST:event_btnCategoryActionPerformed

  private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
        new NewStoreProduct().setVisible(true);
  }//GEN-LAST:event_btnNewProductActionPerformed

  private void btnViewEditDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEditDeleteActionPerformed
            new ViewEditDeleteProduct().setVisible(true);
  }//GEN-LAST:event_btnViewEditDeleteActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  new ChangePassword(user_email).setVisible(true);    // TODO add your handling code here:
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new ViewBillsAndPlacedOrder().setVisible(true);    // TODO add your handling code here:
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   new PlaceOrder().setVisible(true);
  }//GEN-LAST:event_jButton4ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Home(null).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCategory;
  private javax.swing.JButton btnNewProduct;
  private javax.swing.JButton btnViewEditDelete;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lbl_Email;
  private javax.swing.JPanel panel_admin;
  // End of variables declaration//GEN-END:variables

private void initial_setup() {
  frameSizeLocation();
  button_control();
  }  
  
  private void button_control() {
     if (!user_email.equals("admin@admin.com")){
      System.out.println("its not admin ");
      hideButtons_forAdmin();

      
    }else{
        System.out.println("its admin ");
      showButtons_forAdmin();
    }
  }

  private void hideButtons_forAdmin() {
    panel_admin.setVisible(false);
  }

  private void showButtons_forAdmin() {
    panel_admin.setVisible(true);

  }
  private void frameSizeLocation() {
    int  height =  global.GlobalVariables.windowHeight;
    int  width =  global.GlobalVariables.windowWidth;
    int x = global.GlobalVariables.windowLocX;
    int y = global.GlobalVariables.windowLocY;
//    setSize(width, height);
//    setLocation(200,100);
    setBounds(x,y,width,height);

  }  

  
}
