/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store;

import Dao.PurchaseDao;
import Dao.TempPurchaseDao;
import com.toedter.calendar.JDateChooser;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JTable;
import model.Purchase;
import model.TempPurchase;

/**
 *
 * @author JovenLoba
 */
public class SavePurchase extends javax.swing.JFrame {
  static ArrayList publist = null;
  static String user_Email= null;

  /**
   * Creates new form SavePurchase
   */
  public SavePurchase(ArrayList list, String email) {
    initComponents();
    frameSizeLocation();
    publist = list;
    user_Email= email;
    
    jDateChooser1.setDateFormatString("dd/MM/yyyy");
    Date date = new Date();
    jDateChooser1.setDate(date);

    
            
  }
  private void frameSizeLocation() {
    int  height =  global.GlobalVariables.windowCategoryHeight;
    int  width =  global.GlobalVariables.windowCategoryWidth;
    int x = 600;
    int y = 250;
//    setSize(width, height);
//    setLocation(200,100);
    setBounds(x,y,width,height);
    
   }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    txtStore = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    btn_save = new javax.swing.JButton();
    jDateChooser1 = new com.toedter.calendar.JDateChooser();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setText("Store");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 68, 83, -1));

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
    jButton1.setText("Exit");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 14, -1, -1));
    getContentPane().add(txtStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 65, 328, -1));

    jLabel2.setText("Date");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 126, -1, -1));

    btn_save.setText("Save");
    btn_save.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_saveActionPerformed(evt);
      }
    });
    getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 182, 150, 50));
    getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 120, 206, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
    save();
  }//GEN-LAST:event_btn_saveActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(SavePurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(SavePurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(SavePurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(SavePurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new SavePurchase(null,null).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_save;
  private javax.swing.JButton jButton1;
  private com.toedter.calendar.JDateChooser jDateChooser1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField txtStore;
  // End of variables declaration//GEN-END:variables

  private void save() {
//    LocalDate currentdate = LocalDate.now();
//    System.out.println("current date : "+ currentdate);
    
//    String store =  txtStore.getText();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
    String mdate = sdf.format(jDateChooser1.getDate());
    String store = txtStore.getText();
    System.out.println("date :"+mdate);
    
    
//    get all the values from table
    listData(publist,mdate, store);  
    // delete data from temp purchase
    TempPurchaseDao.delete_from_temp_email(user_Email);
    setVisible(false);
     
    
    
    
    
}

  private void listData(ArrayList list ,String mdate,String store) {
 Iterator<TempPurchase> itr = list.iterator();
      while(itr.hasNext()){
        TempPurchase recObj = itr.next();
        String name = recObj.getName();
        String category = recObj.getCategory();
        Integer quantity = recObj.getQuantity();
        Double price = recObj.getPrice();
        Double total  = recObj.getTotal();
        String createdby = recObj.getCreatedby();
        System.out.println(" name :"+ name + ""
          + ", category :"+ category
          + ", quantity :"+ quantity
          + ", price :" + price
          + ", total :" + total
          + ", createdby  :" + createdby
                + ", entered date  :" + mdate
          + "");
        
        Purchase data = new Purchase();
        data.setName(name);
        data.setCategory(category);
        data.setQuantity(quantity);
        data.setPrice(price);
        data.setTotal(total);
        data.setCreatedby(createdby);
        data.setPurchase_from(store);
        data.setPurchase_date(mdate);
        PurchaseDao.save(data);
        
      }        
  }
  
  
}
