/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store;

import Dao.UserDao;
import Database.Common_Var;
import Database.DatabaseHandler;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author JovenLoba
 */
public class StoreLogin extends javax.swing.JFrame {

  DatabaseHandler handler;  
  
  public StoreLogin() {
    initComponents();
    frameSizeLocation();
    handler =  DatabaseHandler.getInstance();
    Common_Var.showmessage = false;    
  }
  private void frameSizeLocation() {
    int  height =  global.GlobalVariables.windowHeight;
    int  width =  global.GlobalVariables.windowWidth;
    int x = global.GlobalVariables.windowLocX;
    int y = global.GlobalVariables.windowLocY;
//    setSize(width, height);
//    setLocation(200,100);
    setBounds(x,y,width,height);

  }    

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    txtPassword = new javax.swing.JPasswordField();
    btn_Login = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();
    btnRegister = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txtEmail = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
    jButton1.setText("Exit");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 40, 100, 40));

    jPanel1.setBackground(new java.awt.Color(208, 242, 242));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 112, 224, -1));

    btn_Login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btn_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
    btn_Login.setText("Login");
    btn_Login.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_LoginActionPerformed(evt);
      }
    });
    jPanel1.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 201, 120, 40));

    btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
    btnCancel.setText("Cancel");
    jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 120, 40));

    btnRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
    btnRegister.setText("Register");
    jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setText("Email");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 64, 137, -1));

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel2.setText("Password");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

    txtEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 64, 224, -1));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 590, 350));

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/storeHome.png"))); // NOI18N
    jLabel3.setText("jLabel3");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1380, 800));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int a = JOptionPane.showConfirmDialog(null, "Do you want to exit Application","select",JOptionPane.YES_NO_OPTION);
    if (a == 0){
      System.exit(0);
    }else{
      System.out.println("Pressed no");
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
    String email = txtEmail.getText();
    String password = txtPassword.getText();
    User user = null;
    user = UserDao.login(email, password);
    if (user==null){
      String html_message =
         "<html><b style=\"color:red\"; \"font-size:2rem\";> Email / Password Invalid </b>      </html>"   ;  
      JOptionPane.showMessageDialog(null, html_message,"Message",JOptionPane.ERROR_MESSAGE);
    }else{ 
      if (user.getStatus().equals("false")){
        String html_message =
           "<html><b style=\"color:Blue\"; \"font-size:2rem\";> Your status should be approved by the Administrator  </b>      </html>"   ;  
        ImageIcon icon = new ImageIcon("src/popupicon/wait.png");
        JOptionPane.showMessageDialog(null, html_message,"Message",JOptionPane.INFORMATION_MESSAGE,icon);
        clear();
      }else{
       System.out.println("you are logged in"); 
       setVisible(false);
       new Home(email).setVisible(true);
      }
       
    }
  }//GEN-LAST:event_btn_LoginActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(StoreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(StoreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(StoreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(StoreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new StoreLogin().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnRegister;
  private javax.swing.JButton btn_Login;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField txtEmail;
  private javax.swing.JPasswordField txtPassword;
  // End of variables declaration//GEN-END:variables

  private void clear() {
    txtEmail.setText("");
    txtPassword.setText("");
     btn_Login.setEnabled(false);

  }
}
