/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store;

import Dao.CategoryDao;
import Dao.ProductDao;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Category;
import model.Product;

/**
 *
 * @author JovenLoba
 */
public class ViewEditDeleteProduct extends javax.swing.JFrame {

  /**
   * Creates new form ViewEditDeleteProduct
   */
  public ViewEditDeleteProduct() {
    initComponents();
    frameSizeLocation();
  }
    private void frameSizeLocation() {
    int  height =  global.GlobalVariables.windowHeight;
    int  width =  global.GlobalVariables.windowWidth;
    int x = 350 ;
    int y = 100;
//    setSize(width, height);
//    setLocation(200,100);
    setBounds(x,y,width,height);

  } 

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txtName = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    cbCategory = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    txtPrice = new javax.swing.JTextField();
    btn_Delete = new javax.swing.JButton();
    btn_Cancel = new javax.swing.JButton();
    lbl_Id = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    txtCost = new javax.swing.JTextField();
    btn_Update = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
    jButton1.setText("Exit");
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, -1, 40));

    jPanel1.setBackground(new java.awt.Color(221, 242, 242));

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Id", "Name", "Category", "Cost", "Price"
      }
    ));
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(38, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(54, 54, 54)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(79, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 670, 560));

    jPanel2.setBackground(new java.awt.Color(235, 255, 255));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setText("ID:");
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, -1));

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setText("Name");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 80, -1));

    txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    txtName.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtNameKeyReleased(evt);
      }
    });
    jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 270, 30));

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel5.setText("Category");
    jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, -1));

    cbCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jPanel2.add(cbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 270, 30));

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel4.setText("Price");
    jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 80, 20));

    txtPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtPriceKeyReleased(evt);
      }
      public void keyTyped(java.awt.event.KeyEvent evt) {
        txtPriceKeyTyped(evt);
      }
    });
    jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 270, 30));

    btn_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
    btn_Delete.setText("Delete");
    btn_Delete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_DeleteActionPerformed(evt);
      }
    });
    jPanel2.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 100, 40));

    btn_Cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btn_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
    btn_Cancel.setText("Cancel");
    btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_CancelActionPerformed(evt);
      }
    });
    jPanel2.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 100, 40));

    lbl_Id.setText("jLabel6");
    jPanel2.add(lbl_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, -1));

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel6.setText("Cost");
    jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

    txtCost.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        txtCostKeyTyped(evt);
      }
    });
    jPanel2.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 270, -1));

    btn_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
    btn_Update.setText("Update");
    btn_Update.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_UpdateActionPerformed(evt);
      }
    });
    jPanel2.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 110, 40));

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 540, 430));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/storeHome.png"))); // NOI18N
    jLabel1.setText("jLabel1");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 790));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    fill_Table();
    fill_combo();
  }//GEN-LAST:event_formComponentShown

  private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
  validateFields();
  }//GEN-LAST:event_txtNameKeyReleased

  private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
    validateFields();
  }//GEN-LAST:event_txtPriceKeyReleased

  private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
    char c = evt.getKeyChar();
    if ( !(Character.isDigit(c)) && c !=KeyEvent.VK_PERIOD){
      getToolkit().beep();
      evt.consume();
    }else if(c==KeyEvent.VK_PERIOD && txtPrice.getText().indexOf(".")>-1 ){
      getToolkit().beep();
      evt.consume();
    } else if (txtPrice.getText().length()>=10){
      getToolkit().beep();
      evt.consume();
    } if(txtPrice.getText().length()==9){
      txtPrice.setText(txtPrice.getText().substring(1));
    }
  }//GEN-LAST:event_txtPriceKeyTyped

  private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
    int id =Integer.parseInt(lbl_Id.getText());
    String name = txtName.getText();
    String category = (String)cbCategory.getSelectedItem();
    Double cost = Double.valueOf(txtCost.getText());
    Double price = Double.valueOf(txtPrice.getText());

    Product product = new Product();
    product.setId(id);
    product.setName(name);
    product.setCategory(category);
    product.setPrice(price);
    product.setCost(cost);

    ProductDao.update(product);
    setVisible(false);
    new ViewEditDeleteProduct().setVisible(true);
  }//GEN-LAST:event_btn_UpdateActionPerformed

  private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
    int id =Integer.parseInt(lbl_Id.getText());
    String name = txtName.getText();

    int a = JOptionPane.showConfirmDialog(null,"Confirm to id '"+id+"' , Product : '"+ name+"'", "Select", JOptionPane.YES_NO_OPTION);
    if (a==0){
      ProductDao.delete(id);
      setVisible(false);
      new ViewEditDeleteProduct().setVisible(true);

    }
  }//GEN-LAST:event_btn_DeleteActionPerformed

  private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
    clear();
  }//GEN-LAST:event_btn_CancelActionPerformed

  private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    int index = jTable1.getSelectedRow();
    
    TableModel model=  jTable1.getModel();
    
    String id = model.getValueAt(index, 0).toString();
    String name = model.getValueAt(index, 1).toString();
    String category = model.getValueAt(index, 2).toString();
    String cost = model.getValueAt(index,3).toString();
    String price = model.getValueAt(index,4).toString();
    
    lbl_Id.setText(id);
    txtName.setText(name);
    cbCategory.setSelectedItem(category);
    txtCost.setText(cost);
    txtPrice.setText(price);
    
    
    

    cbCategory.removeAllItems();
    cbCategory.addItem(category);
    
    ArrayList<Category> categoryList = CategoryDao.getAllRecords();
    Iterator<Category> categoryItr = categoryList.iterator();
    while(categoryItr.hasNext()){
      Category categoryObj = categoryItr.next();
      if (!categoryObj.getName().equals(category)){
        cbCategory.addItem(categoryObj.getName());
      }
    }
        validateFields();    
  }//GEN-LAST:event_jTable1MouseClicked

  private void txtCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostKeyTyped
       char c = evt.getKeyChar();
    if ( !(Character.isDigit(c)) && c !=KeyEvent.VK_PERIOD){
      getToolkit().beep();
      evt.consume();
    }else if(c==KeyEvent.VK_PERIOD && txtCost.getText().indexOf(".")>-1 ){
      getToolkit().beep();
      evt.consume();
    } else if (txtCost.getText().length()>=10){
      getToolkit().beep();
      evt.consume();
    } if(txtCost.getText().length()==9){
      txtCost.setText(txtCost.getText().substring(1));
    }
  }//GEN-LAST:event_txtCostKeyTyped

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ViewEditDeleteProduct().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Cancel;
  private javax.swing.JButton btn_Delete;
  private javax.swing.JButton btn_Update;
  private javax.swing.JComboBox<String> cbCategory;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JLabel lbl_Id;
  private javax.swing.JTextField txtCost;
  private javax.swing.JTextField txtName;
  private javax.swing.JTextField txtPrice;
  // End of variables declaration//GEN-END:variables

public void validateFields(){
  String name = txtName.getText();
  String mprice = txtPrice.getText();
  String category = (String)cbCategory.getSelectedItem();
  
  if (name.equals("") || mprice.equals("")  || category == null ){
    btn_Update.setEnabled(false);
    btn_Delete.setEnabled(false);
  } else if((!name.equals("")) && (!mprice.equals("")) && !(category ==null)   ){
    btn_Update.setEnabled(true);
    btn_Delete.setEnabled(true);
    
  }
}    
public void clear(){
    txtName.setText("");
    txtPrice.setText("");
    txtCost.setText("");
//    cbCategory.set
    btn_Update.setEnabled(false);
    btn_Delete.setEnabled(false);
    
}
private void fill_combo() {
    ArrayList<Category> list = CategoryDao.getAllRecords();
    Iterator<Category> itr =  list.iterator();
    while (itr.hasNext()){
     Category categoryObj = itr.next();
     cbCategory.addItem(categoryObj.getName());

    }
  }
  private void fill_Table() {
    DefaultTableModel  dtm = (DefaultTableModel) jTable1.getModel();
    // get all records rom products
    ArrayList<Product> list = ProductDao.getAllRcords();
    
    Iterator<Product> itr = list.iterator();
    while (itr.hasNext()){
      Product productobj = itr.next();
      dtm.addRow(new Object[]{     
        productobj.getId() , 
        productobj.getName(), 
        productobj.getCategory(), 
        productobj.getCost(),
        productobj.getPrice()
      });
    
    }
  }

}

