/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store;


import Dao.BillDao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;

/**
 *
 * @author JovenLoba
 */
public class ViewBillsAndPlacedOrder extends javax.swing.JFrame {

  /**
   * Creates new form ViewBillsAndPlacedOrder
   */
  public ViewBillsAndPlacedOrder() {
    initComponents();
    frameSizeLocation();
    SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
    Date date = new Date();
    String today = dFormat.format(date);
    txtDate.setText(today);
  }

  public void getTAbleDetails() {
    String date = txtDate.getText();
    String date_arrange_by = cbArrange.getSelectedItem().toString();
    System.out.println("date arrange by " + date_arrange_by + "\ndate: " + date);
    DefaultTableModel dtm = (DefaultTableModel) tableView.getModel();
//    remove all records in table
    dtm.setRowCount(0);

    ArrayList<Bill> list = null;

    if (date_arrange_by == "Ascending") {
      list = BillDao.BillGetAllRecordsAscending(date);

    } else {
      list = BillDao.BillGetAllRecordsDescending(date);
    }
    // populate the table

    Iterator<Bill> itr = list.iterator();
    while (itr.hasNext()) {
      Bill billObj = itr.next();
      dtm.addRow(new Object[]{
        billObj.getId(),
        billObj.getName(),
        billObj.getMobile(),
        billObj.getEmail(),
        billObj.getTotal(),
        billObj.getDate()
      });

    }

  }

  private void frameSizeLocation() {
    int height = global.GlobalVariables.windowHeight;
    int width = global.GlobalVariables.windowWidth;
    int x = global.GlobalVariables.windowLocX;
    int y = global.GlobalVariables.windowLocY;
//    setSize(width, height);
//    setLocation(200,100);
    setBounds(x, y, width, height);

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    txtDate = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    cbArrange = new javax.swing.JComboBox<>();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tableView = new javax.swing.JTable();
    jLabel4 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setResizable(false);
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setText("View Bilss and Order Placed");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, 305, 29));

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
    jButton1.setText("Close");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, -1, -1));

    jPanel2.setBackground(new java.awt.Color(214, 242, 242));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setText("Filter Date");
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

    txtDate.setText("jTextField1");
    txtDate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtDateActionPerformed(evt);
      }
    });
    txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        txtDateKeyPressed(evt);
      }
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtDateKeyReleased(evt);
      }
    });
    jPanel2.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 161, 30));

    jLabel3.setText("Change Order by Id");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

    cbArrange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));
    cbArrange.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbArrangeActionPerformed(evt);
      }
    });
    jPanel2.add(cbArrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 239, -1));

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 300, 300));

    jPanel1.setBackground(new java.awt.Color(214, 242, 242));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    tableView.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null}
      },
      new String [] {
        "Id", "Name", "Mobile", "Email", "Bill Total", "Date"
      }
    ));
    tableView.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableViewMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tableView);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 930, 500));

    jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
    jLabel4.setText("Click on Row to Open Bill");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, -1));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 990, 600));

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/storeHome.png"))); // NOI18N
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void txtDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyReleased
    getTAbleDetails();    // TODO add your handling code here:

  }//GEN-LAST:event_txtDateKeyReleased

  private void txtDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyPressed
    // TODO add your handling code here:

  }//GEN-LAST:event_txtDateKeyPressed

  private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed

  }//GEN-LAST:event_txtDateActionPerformed

  private void cbArrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbArrangeActionPerformed
    getTAbleDetails();
  }//GEN-LAST:event_cbArrangeActionPerformed

  private void tableViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewMouseClicked
    int index = tableView.getSelectedRow();
    TableModel model = tableView.getModel();
    String id = model.getValueAt(index, 0).toString();
    String path = "C:\\Users\\JovenLoba\\Desktop\\outputfiles\\report_";
    System.out.println("path");
    OpenPdf.OpenPdf.openById(path, Integer.parseInt(id));

  }//GEN-LAST:event_tableViewMouseClicked

  private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    getTAbleDetails();
  }//GEN-LAST:event_formComponentShown

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ViewBillsAndPlacedOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ViewBillsAndPlacedOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ViewBillsAndPlacedOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ViewBillsAndPlacedOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ViewBillsAndPlacedOrder().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> cbArrange;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tableView;
  private javax.swing.JTextField txtDate;
  // End of variables declaration//GEN-END:variables
}
